# Generated by Django 4.2.3 on 2023-07-28 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ecommerce.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('first_name', models.CharField(blank=True, max_length=30, null=True, validators=[ecommerce.common.validators.validate_name])),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, validators=[ecommerce.common.validators.validate_name])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
