# Generated by Django 4.2.3 on 2023-08-16 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
